### ISSUE TITLE
Some Recommendations

### ISSUE THREAD

**Issue by JASory** [ivanrj7j/Pi#1]
1. Look into Julia, it's an interpreted language like Python but it uses GMP and MPFR to provide arbitrary precision integers and large floating point numbers. It's much faster and more versatile for demonstrations like this.
2. Provide a test for the algorithms to show that the approximation improves with greater iterations/calculations. E.g at iteration 5  pi-approx = 3.0 at step 5000 pi-approx = .14
3. Allow discussions for this repository in the settings, that way things like these can be mentioned in the discussions instead of an issue
4. A lot of the algorithms are going to be different approaches to exploit the same property, so having some classification system would be useful

**Comment by ivanrj7j** [comment]
- I am planning on creating a simple library for floating point representation (need some more research to do that). I am planning to make a floating point class which stores 2 bits as the digit since 3 only requires 2 bits to represent and use every other bit for represening a decimal places. I am open for suggestions.
- That would be on my to do list.
- Already  opened a discussions tab.
- I need more research for that, give me some ideas on how to classify them

**Comment by JASory** [comment]
I'm not sure how useful writing your own floating point library is. Irrational constants like pi can be (approximately) computed using scaled integers. And it is much easier to write arbitrary-precision arithmetic than an IEE style float. 

Trying to condense the representation by having each decimal represented by 2 bits wouldn't work because pi decimals can take any value between [0;9]. One could drop certain decimal places from pi to let you store more digits, but the actual advantage of this is minimal.
